projects:
  db:
    schemaPath: schema.graphql
    extensions:
      prisma: prisma.yml
      codegen:
        - generator: prisma-binding
          language: typescript 
          output:
            binding: binding.ts