version: '3'
services:
  prisma:
    image: prismagraphql/prisma:${PRISMA_VERSION}
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: db
            port: 3306
            user: prisma
            password: prisma
            migrations: true
  db:
    image: mysql:5.7
    restart: always
    command: mysqld
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: prisma
      MYSQL_DATABASE: prisma
    ports:
    - "3306:3306"
volumes:
  postgres:
